Us 29 43 dependency injection handling
Hide-Hunt/HideAndHunt pull request #165
Opened 2020-04-01 14:42 UTC by Foebus

First merge to have a base on master, to be able to use dagger everywhere it may be useful in the project

2020-04-04 12:10 UTC, corentin-junod reviewed
Deux petits trucs a changer mais c'est vraiment pas grand chose

2020-04-04 12:10 UTC, Dolpic commented on app/src/androidTest/java/ch/epfl/sdp/authentication/LoginActivityTest.kt
>          //onView(withId(R.id.loginSubmitButton)).perform(click())
Ici il faudrait que le teste test effectivement quelque chose, avec par exemple quelque chose comme : Intents.intended(IntentMatchers.hasComponent(LoginActivity::class.java.name))

2020-04-04 12:10 UTC, Dolpic commented on app/src/main/java/ch/epfl/sdp/MainActivity.kt
> +        binding.newGameButton.setOnClickListener{
Le binding est dupliqué ici, c'est inutile

2020-04-04 23:00 UTC, HVYVince requested changes
MyApplication is a terrible name for something that will supposedly be used in all the codebase transversally. You should name it something like "DaggerApplication" ou "DaggerHideAndHunt". If I understood wrongly the purpose of the MyApplication class then tell me so and I'll approve the stuff

2020-04-04 23:00 UTC, HVYVince commented on app/src/androidTest/java/ch/epfl/sdp/lobby/MyCustomTestRunner.kt
> +class MyCustomTestRunner: AndroidJUnitRunner() {
What is this file used for ? Is it truly necessary ? If this is supposed to be an example of a test to be duplicated by other devs, then perhaps add a comment to explain this and the fact that the file will have to be deleted at clean time when wrapping up the project

2020-04-04 23:00 UTC, HVYVince commented on app/src/main/AndroidManifest.xml
> +        android:name=".dagger.MyApplication"
"MyApplication" does not seem like a good name

2020-04-04 23:00 UTC, HVYVince commented on app/src/main/java/ch/epfl/sdp/MainActivity.kt
> +        binding.newGameButton.setOnClickListener{
Yup

2020-04-04 23:00 UTC, HVYVince commented on app/src/main/java/ch/epfl/sdp/dagger/MyApplication.kt
> +class MyTestApplication: MyApplication(){
MyTestApplication does not seem like a good name either

2020-04-05 15:38 UTC, pauldms commented on app/src/androidTest/java/ch/epfl/sdp/lobby/MyCustomTestRunner.kt
> +class MyCustomTestRunner: AndroidJUnitRunner() {
Yes it is necessary, it "tells" the test classes to inject the test dependencies of "MyTestApplication" instead of the normal ones in "MyApplication"

2020-04-07 11:59 UTC, Foebus commented on app/src/androidTest/java/ch/epfl/sdp/authentication/LoginActivityTest.kt
>          //onView(withId(R.id.loginSubmitButton)).perform(click())
ouais, alors je veux bien mais ce test n'est pas à moi...

2020-04-07 12:14 UTC, Foebus commented on app/src/main/AndroidManifest.xml
> +        android:name=".dagger.MyApplication"
It is the name of the global object used in the entire application, for now only used for dagger but may be used for other things...but I'll look if there are naming convention in android for that

2020-04-07 13:25 UTC, corentin-junod approved these changes

2020-04-07 13:34 UTC, HVYVince approved these changes
Okay

2020-04-07 13:35 UTC, merged