#195 Bug - Null profile pic crashes the app when caching
Hide-Hunt/HideAndHunt pull request #196
Opened 2020-05-21 14:37 UTC by HVYVince

2020-05-21 15:09 UTC, Zorvalt requested changes

2020-05-21 15:09 UTC, Zorvalt commented on app/src/main/java/ch/epfl/sdp/user/UserCache.kt
> +            imageStream.close()
What's the point of opening then immediately closing an input stream ?

2020-05-21 15:09 UTC, Zorvalt commented on app/src/main/java/ch/epfl/sdp/user/UserCache.kt
> +        }
BitmapFactory.decodeFile does not raise any exception : https://developer.android.com/reference/android/graphics/BitmapFactory#decodeFile(java.lang.String)

If the is input stream is needed, tt might be good to only catch related IO exceptions

2020-05-21 23:48 UTC, corentin-junod approved these changes

2020-05-22 09:35 UTC, ProtectedVariable approved these changes

2020-05-22 09:46 UTC, Zorvalt approved these changes

2020-05-22 11:12 UTC, merged