Us 29 create game creation form
Hide-Hunt/HideAndHunt pull request #70
Opened 2020-03-18 12:57 UTC by Dolpic

2020-03-25 09:06 UTC, HVYVince reviewed
A priori okay, je te laisse merger master et adresser les commentaires que j'ai fait avant de valider

2020-03-25 09:06 UTC, HVYVince commented on app/src/main/res/layout/activity_game_creation.xml
> +                    android:text="Name" />
Pourquoi tu utilises pas une valeur dans le fichier de string ici ? 
Aussi je vois pas les hint dans tes champs de texte, tu as pas des warning dans android studio à cause de ça ? Si oui, faut les ajouter

2020-03-25 09:06 UTC, HVYVince commented on app/src/main/java/ch/epfl/sdp/lobby/GameCreationActivity.kt
> +            //val lobbyRepo = LobbyRepo(binding.gameName.text, binding.gameDuration.text)
Vire le commentaire à l'occase ;)

2020-03-27 08:28 UTC, HVYVince approved these changes
Okay, but will be conflicting if Thomas' PR is merged before this one

2020-03-27 09:10 UTC, pauldms requested changes
Pretty good, just change the intent to the right lobby class and some minor changes in the layout file

2020-03-27 09:10 UTC, pauldms commented on app/src/main/java/ch/epfl/sdp/lobby/GameCreationActivity.kt
> +            val intent = Intent(this@GameCreationActivity, LobbyActivity::class.java)
Should launch the new Lobby activity GameLobbyActivity

2020-03-27 09:10 UTC, pauldms commented on app/src/main/java/ch/epfl/sdp/MainActivity.kt
> +            val intent = Intent(this@MainActivity, GameCreationActivity::class.java)
Should test for the new lobby activity GameLobbyActivity

2020-03-27 09:10 UTC, pauldms commented on app/src/main/res/layout/activity_game_creation.xml
> +                    android:id="@+id/textView8"
Try giving your views id names that are significant, like game_name_view or something like this

2020-03-27 09:10 UTC, pauldms commented on app/src/main/res/layout/activity_game_creation.xml
> +                    android:text="Name" />
+1, faut éviter les string hardcodées

2020-03-27 09:10 UTC, pauldms commented on app/src/main/res/layout/activity_game_creation.xml
> +                    android:text="120" />
See previous comment on hardcoded strings

2020-03-27 09:35 UTC, pauldms approved these changes
Ok to merge

2020-03-31 18:20 UTC, merged